# Generated by Django 5.1.7 on 2025-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='food_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='sugars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodanalysis',
            name='image',
            field=models.ImageField(upload_to='food_images/'),
        ),
    ]
