# Generated by Django 5.1.7 on 2025-05-09 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hydration_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_size', models.FloatField()),
                ('water_goal', models.FloatField()),
                ('active_start', models.TimeField(default='0:00')),
                ('active_end', models.TimeField(default='23:59')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=256)),
                ('calories', models.IntegerField(default=1)),
                ('allergen_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergen', to='NutritionGuidance.allergen')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='NutritionGuidance.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=32)),
                ('day', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')])),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='NutritionGuidance.meal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='NutritionGuidance.ingredient')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='NutritionGuidance.recipe')),
            ],
            options={
                'unique_together': {('recipe_id', 'ingredient_id')},
            },
        ),
    ]
