# Generated by Django 5.1.7 on 2025-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='acid_peptic_disorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alcohol_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alcohol_units_per_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='allergy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allergy_severity',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='anxiety_mood_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='asthma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='convulsions_or_seizure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='covid_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='depression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eating_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='g6pd_deficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='illness_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kidney_urinary_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='medications_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='menstrual_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='municipality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='psychoactive_substance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='recurrent_headaches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stroke_heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suicidal_thoughts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='surgeries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='thyroid_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tuberculosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='User', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
